src/WebApps/CosmeticEshop/Models/Baskets/Basket.cs
using System;
using System.Collections.Generic;
using System.Linq;

namespace CosmeticEshop.Models.Baskets
{
    public record Basket
    {
        // Use property initializer syntax.
        // While this is often more useful for read only 
        // auto implemented properties, it can simplify logic
        // for read/write properties.
        public List<BasketItem> Items { get; init; } = new List<BasketItem>();
        public string UserId { get; init; }

        public decimal Total()
        {
            return Math.Round(Items.Sum(x => (x.Price - x.Sale) * x.Quantity));
        }
    }
}

src/WebApps/CosmeticEshop/Models/Baskets/BasketItem.cs
namespace CosmeticEshop.Models.Baskets
{
    public class BasketItem
    {
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public int Quantity { get; set; }
        public decimal Price { get; set; }
        public decimal Sale { get; set; }

        // product related additional fields
        public string Category { get; set; }
        public string Summary { get; set; }
        public string Description { get; set; }
        public string ImageFile { get; set; }
        public bool IsAvaiable { get; set; }
    }
}

src/WebApps/CosmeticEshop/Models/Baskets/BasketItemDto.cs
namespace CosmeticEshop.Models.Baskets
{
    public class BasketItemDto
    {
        public string ProductId { get; set; }
        public int Quantity { get; set; }
    }
}

src/WebApps/CosmeticEshop/Controllers/BasketController.cs
using AutoMapper;

using CosmeticEshop.Extensions;
using CosmeticEshop.Models.Baskets;
using CosmeticEshop.Models.Order;
using CosmeticEshop.Services.Interfaces;
using CosmeticEshop.SignalR;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using Microsoft.Extensions.Logging;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CosmeticEshop.Controllers
{
    public class BasketController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly IProductService _productService;
        private readonly ISystemService _systemService;
        private readonly IMapper _mapper;
        private readonly IHubContext<BasketHub, IBasketHub> _hubContext;

        private readonly ILogger<BasketController> _logger;

        public BasketController(IBasketService basketService, IProductService productService, ISystemService systemService, ILogger<BasketController> logger, IMapper mapper, IHubContext<BasketHub, IBasketHub> hubContext)
        {
            _basketService = basketService;
            _productService = productService;
            _systemService = systemService;
            _logger = logger;
            _mapper = mapper;
            _hubContext = hubContext;
        }

        public async Task<IActionResult> Index()
        {
            var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
            var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            ViewBag.shopContact = shopContact;
            ViewBag.menus = menus;
            ViewBag.basket = basket;

            return View();
        }
        public async Task<IActionResult> SyncBasket()
        {
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);
            return PartialView("_MiniCartView", basket);
        }
        public async Task<IActionResult> GetBasket()
        {
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);
            return Json(basket);
        }

        public async Task<IActionResult> EmptyBasket()
        {
            var currentBasket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            var basket = new Basket
            {
                UserId = currentBasket.UserId
            };
            await _basketService.UpdateBasketAsync(basket);

            await _hubContext.Clients.Group(basket.UserId).SetBasket(basket.Items.Count);

            return NoContent();
        }
        
        public async Task<IActionResult> AddItemToBasket(BasketItemDto dto)
        {
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            if (basket.Items.Any(x => x.ProductId == dto.ProductId))
            {
                var currentItem = basket.Items.First(x => x.ProductId == dto.ProductId);
                currentItem.Quantity += dto.Quantity;
            } else
            {
                basket.Items.Add(_mapper.Map<BasketItem>(dto));
            }

            await _basketService.UpdateBasketAsync(basket);

            await _hubContext.Clients.Group(basket.UserId).SetBasket(basket.Items.Count);

            return NoContent();
        }
        public async Task<IActionResult> SetQuantityProductInBasket(BasketItemDto dto)
        {
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            if (basket.Items.Any(x => x.ProductId == dto.ProductId))
            {
                var currentItem = basket.Items.First(x => x.ProductId == dto.ProductId);
                currentItem.Quantity = dto.Quantity;
            } else
            {
                basket.Items.Add(_mapper.Map<BasketItem>(dto));
            }

            await _basketService.UpdateBasketAsync(basket);

            await _hubContext.Clients.Group(basket.UserId).SetBasket(basket.Items.Count);

            return NoContent();
        }
        
        public async Task<IActionResult> RemoveItemFromBasket(string productId)
        {
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            basket.Items.Remove(basket.Items.First(x => x.ProductId == productId));

            await _basketService.UpdateBasketAsync(basket);

            await _hubContext.Clients.Group(basket.UserId).SetBasket(basket.Items.Count);
            return NoContent();
        }

        public async Task<IActionResult> Checkout()
        {
            var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
            var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            ViewBag.shopContact = shopContact;
            ViewBag.menus = menus;
            ViewBag.basket = basket;

            var orderDetailModel = new OrderDetailModel
            {
                Items = _mapper.Map<IEnumerable<OrderDetail>>(basket.Items)
            };
            return View(orderDetailModel);
        }
        
        public async Task<IActionResult> OrderSuccess()
        {
            var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
            var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);

            ViewBag.shopContact = shopContact;
            ViewBag.menus = menus;
            ViewBag.basket = new Basket();

            return View();
        }
        public async Task<IActionResult> Order(OrderDetailModel order)
        {
            if (!ModelState.IsValid)
            { // re-render the view when validation failed.
                var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
                var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);
                var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

                ViewBag.shopContact = shopContact;
                ViewBag.menus = menus;
                ViewBag.basket = basket;

                order.Items = _mapper.Map<IEnumerable<OrderDetail>>(basket.Items);

                return View(nameof(Checkout), order);
            } else
            {
                await _basketService.Checkout(order);

                return RedirectToAction(nameof(OrderSuccess));
            }
        }
    }
}

src/WebApps/CosmeticEshop/Views/Basket/Checkout.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CosmeticEshop.Models.Order.OrderDetailModel
@{
    ViewData["Title"] = "Đặt đơn hàng";
    ViewData["Header"] = new List<Header>
{
        new Header
        {
            Controller = "Home",
            Text = "Trang chủ",
            Current = false
        },
        new Header
        {
            Text = "Đặt đơn hàng",
            Current = true
        }
    };
}

<!--== Start Checkout Page Wrapper ==-->
<div id="checkout-page-wrapper" class="pt-90 pt-md-60 pt-sm-50 pb-50 pb-md-20 pb-sm-10">
    <div class="container">
        <form asp-action="Order" method="post" asp-controller="Basket">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="row">
                <div class="col-lg-6">
                    <!-- Checkout Form Area Start -->
                    <div class="checkout-billing-details-wrap">
                        <h2>Thông tin hóa đơn</h2>
                        <div class="billing-form-wrap">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="single-input-item">
                                        <label asp-for="BuyerFirstName" class="required" >Tên</label>
                                        <input asp-for="BuyerFirstName" placeholder="Tên" />
                                        <span asp-validation-for="BuyerFirstName" class="text-danger" />
                                    </div>
                                </div>

                                <div class="col-md-6">
                                    <div class="single-input-item">
                                        <label asp-for="BuyerLastName">Họ và tên đệm</label>
                                        <input asp-for="BuyerLastName" placeholder="Họ và tên đệm" />
                                        <span asp-validation-for="BuyerLastName" class="text-danger" />
                                    </div>
                                </div>
                            </div>

                            <div class="single-input-item">
                                <label asp-for="BuyerEmailAddress" class="required" >Email</label>
                                <input asp-for="BuyerEmailAddress" placeholder="Địa chỉ email" />
                                <span asp-validation-for="BuyerEmailAddress" class="text-danger"></span>
                            </div>

                            <div class="single-input-item">
                                <label asp-for="BuyerAddressLine" class="required">Địa chỉ</label>
                                <input asp-for="BuyerAddressLine" placeholder="Địa chỉ" />
                                <span asp-validation-for="BuyerAddressLine" class="text-danger"></span>
                            </div>

                            <div class="single-input-item">
                                <label asp-for="BuyerState" class="required">Tỉnh/Thành phố</label>
                                <input asp-for="BuyerState" placeholder="Tỉnh/Thành phố" />
                                <span asp-validation-for="BuyerState" class="text-danger"></span>
                            </div>

                            <div class="single-input-item">
                                <label asp-for="BuyerPhoneNumber" class="required">Số điện thoại</label>
                                <input asp-for="BuyerPhoneNumber" placeholder="Số điện thoại" />
                                <span asp-validation-for="BuyerPhoneNumber" class="text-danger"></span>
                            </div>

                            <div class="checkout-box-wrap">
                                <div class="single-input-item">
                                    <div class="custom-control custom-checkbox">
                                        <input type="checkbox" asp-for="ShippingDifferentAddress" id="ship_to_different" class="custom-control-input" />
                                        <label asp-for="ShippingDifferentAddress" for="ship_to_different" class="custom-control-label">Giao hàng tới địa chỉ khác?</label>
                                    </div>
                                </div>
                                <div class="ship-to-different single-form-row">
                                    <div class="row">
                                        <div class="col-md-6">
                                            <div class="single-input-item">
                                                <label asp-for="ReceiverFirstName" class="required">Tên</label>
                                                <input asp-for="ReceiverFirstName" placeholder="Tên" />
                                                <span asp-validation-for="ReceiverFirstName" class="text-danger" />
                                            </div>
                                        </div>

                                        <div class="col-md-6">
                                            <div class="single-input-item">
                                                <label asp-for="ReceiverLastName" >Họ và tên đệm</label>
                                                <input asp-for="ReceiverLastName" placeholder="Họ và tên đệm" />
                                                <span asp-validation-for="ReceiverLastName" class="text-danger" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="single-input-item">
                                        <label asp-for="ReceiverEmailAddress" class="required" >Email</label>
                                        <input asp-for="ReceiverEmailAddress" placeholder="Địa chỉ email" />
                                        <span asp-validation-for="ReceiverEmailAddress" class="text-danger"></span>
                                    </div>

                                    <div class="single-input-item">
                                        <label asp-for="ReceiverAddressLine" class="required">Địa chỉ</label>
                                        <input asp-for="ReceiverAddressLine" placeholder="Địa chỉ" />
                                        <span asp-validation-for="ReceiverAddressLine" class="text-danger"></span>
                                    </div>

                                    <div class="single-input-item">
                                        <label asp-for="ReceiverState" class="required">Thành phố</label>
                                        <input asp-for="ReceiverState" placeholder="Thành phố" />
                                        <span asp-validation-for="ReceiverState" class="text-danger"></span>
                                    </div>

                                    <div class="single-input-item">
                                        <label asp-for="ReceiverPhoneNumber" class="required">Số điện thoại</label>
                                        <input asp-for="ReceiverPhoneNumber" placeholder="Số điện thoại" />
                                        <span asp-validation-for="ReceiverPhoneNumber" class="text-danger"></span>
                                    </div>

                                </div>
                            </div>

                            <div class="single-input-item">
                                <label asp-for="Note">Ghi chú</label>
                                <textarea asp-for="Note" cols="30" rows="3" placeholder="Ghi chú cho đơn hàng. Ví dụ: Yêu cầu đặc biệt khi giao hàng"></textarea>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="col-lg-6 col-xl-5 ml-auto">
                    <!-- Checkout Page Order Details -->
                    <div class="order-details-area-wrap">
                        <h2>Chi tiết đơn hàng</h2>

                        <div class="order-details-table table-responsive">
                            <table class="table table-borderless">
                                <thead>
                                    <tr>
                                        <th>Sản phẩm</th>
                                        <th>Thành tiền</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach (var item in Model.Items)
                                    {
                                        <tr class="cart-item">
                                            <td><span class="product-title">@item.ProductName</span> <span class="product-quantity">&#215;  @item.Quantity</span></td>
                                            <td>@((item.Price * item.Quantity).ToVNString())</td>
                                        </tr>
                                    }
                                </tbody>
                                <tfoot>
                                    <tr class="cart-subtotal">
                                        <th>Tạm tính</th>
                                        <td>@Model.Items.Sum(x => x.Price * x.Quantity).ToVNString()</td>
                                    </tr>
                                    <tr class="shipping">
                                        <th>Giảm giá</th>
                                        <td>@Model.Items.Sum(x => x.Sale * x.Quantity).ToVNString()</td>
                                    </tr>
                                    <tr class="final-total">
                                        <th>Thành tiền</th>
                                        <td><span class="total-amount">@Model.Items.Sum(x => (x.Price - x.Sale) * x.Quantity).ToVNString()</span></td>
                                    </tr>
                                </tfoot>
                            </table>
                        </div>

                        <div class="order-details-footer">
                            <p>
                                Dữ liệu cá nhân của bạn sẽ được sử dụng để xử lý đơn đặt hàng, hỗ trợ trải nghiệm của bạn trên toàn bộ trang web này.
                            </p>
                            <div class="custom-control custom-checkbox mt-10">
                                <input asp-for="AcceptPrivacy" required class="custom-control-input" title="Bạn cần đồng ý các điều khoản và thỏa thuận để tiếp tục"/>
                                <label asp-for="AcceptPrivacy" class="custom-control-label">Tôi đồng ý với các điều khoản và điều kiện của trang web</label>
                                <span asp-validation-for="AcceptPrivacy" class="text-danger"></span>
                            </div>

                            <button type="submit" class="btn btn-full btn-black mt-26">Đặt hàng</button>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
</div>
<!--== End Checkout Page Wrapper ==-->

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

<script>
    $(function () {
        @if (Model.ShippingDifferentAddress) {
            <text>
            $(".ship-to-different").slideToggle("100");
            </text>
        }
    });
</script>
}

src/WebApps/CosmeticEshop/Views/Basket/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Giỏ hàng";
    ViewData["Header"] = new List<Header>
{
        new Header
        {
            Controller = "Home",
            Text = "Trang chủ",
            Current = false
        },
        new Header
        {
            Text = "Giỏ hàng",
            Current = true
        }
    };

}


<script src="~/js/angularjs-controller/basketController.js"></script>
<!--== Start Cart Page Wrapper ==-->
<div id="cart-page-wrapper" class="pt-86 pt-md-56 pt-sm-46 pb-50 pb-md-20 pb-sm-10" ng-app="basket-app">
    <div class="container" ng-controller="BasketController as basket">
        <div class="row" ng-if="items.length > 0">
            <div class="col-lg-8">
                <div class="shopping-cart-list-area">
                    <div class="shopping-cart-table table-responsive">
                        <table class="table table-bordered text-center">
                            <thead>
                                <tr>
                                    <th>Sản phẩm</th>
                                    <th>Giá</th>
                                    <th>Số lượng</th>
                                    <th>Thành tiền</th>
                                </tr>
                            </thead>

                            <tbody>
                                <tr ng-repeat="item in items">
                                    <td class="product-list">
                                        <div class="cart-product-item d-flex align-items-center">
                                            <div class="remove-icon">
                                                <button ng-click="basket.remove(item.productId);"><i class="fa fa-trash-o"></i></button>
                                            </div>
                                            <a ng-href="/product/detail/{{item.productId}}" class="product-thumb">
                                                <img src="{{item.imageFile}}" alt="{{item.productName}}" />
                                            </a>
                                            <a ng-href="/product/detail/{{item.productId}}" class="product-name">{{item.productName}}</a>
                                        </div>
                                    </td>
                                    <td>
                                        <div ng-if="item.sale > 0">
                                            <del class="oldPrice">{{item.price}}</del>
                                            <span class="price">{{item.price - item.sale}}</span>
                                        </div>
                                        <div ng-if="item.sale === 0">
                                            <span class="price">{{item.price}}</span>
                                        </div>
                                    </td>
                                    <td>
                                        <div class="pro-qty">
                                            <input type="text" class="quantity" ng-model="item.quantity" />
                                            <a ng-click="basket.changeQuantity(item.productId, 1)" class="inc qty-btn">+</a>
                                            <a ng-click="basket.changeQuantity(item.productId, -1)" class="dec qty-btn">-</a>
                                        </div>
                                    </td>
                                    <td>
                                        <span class="price">{{(item.price - item.sale) * item.quantity}}</span>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div>

                    <div class="cart-coupon-update-area d-sm-flex justify-content-between align-items-center">
                        <div class="cart-update-buttons mt-xs-14">
                            <button class="btn-clear-cart" ng-click="basket.removeBasket()">Xóa giỏ hàng</button>
                            <button class="btn-update-cart" ng-click="basket.updateBasket()">Cập nhật giá</button>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-lg-4">
                <!-- Cart Calculate Area -->
                <div class="cart-calculate-area mt-sm-30 mt-md-30">
                    <h5 class="cal-title">Tổng cộng</h5>

                    <div class="cart-cal-table table-responsive">
                        <table class="table table-borderless">
                            <tr class="cart-sub-total">
                                <th>Tổng giá trị (1)</th>
                                <td>{{basket.getTotalPrice()}}</td>
                            </tr>
                            <tr class="cart-sub-total">
                                <th>Giảm giá (2)</th>
                                <td>{{basket.getTotalSale()}}</td>
                            </tr>
                            <tr class="order-total">
                                <th>Thành tiền (1 - 2)</th>
                                <td><b>{{basket.getTotalPrice() - basket.getTotalSale()}}</b></td>
                            </tr>
                        </table>
                    </div>

                    <div class="proceed-checkout-btn">
                        <a asp-action="Checkout" asp-controller="Basket" class="btn btn-full btn-black">Thanh toán</a>
                    </div>
                </div>
            </div>
        </div>
        <div ng-if="items.length === 0" class="text-center">
            <h2>Bạn chưa có sản phẩm nào trong giỏ hàng</h2>
            <span>Tiếp tục mua sắm</span>
            <a asp-action="Index" asp-controller="Home">Trang chủ</a>
        </div>
    </div>
</div>
<!--== End Cart Page Wrapper ==-->

src/WebApps/CosmeticEshop/Views/Basket/OrderSuccess.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Đặt hàng thành công";
    ViewData["Header"] = new List<Header>
{
        new Header
        {
            Controller = "Home",
            Text = "Trang chủ",
            Current = false
        },
        new Header
        {
            Text = "Đặt hàng thành công",
            Current = true
        }
    };
}

<div id="cart-page-wrapper" class="pt-86 pt-md-56 pt-sm-46 pb-50 pb-md-20 pb-sm-10">
    <div class="container">
        <div class="text-center">
            <h2>Đặt hàng thành công!</h2>
            <p>Cảm ơn bạn đã tin tưởng và đặt hàng của chúng tôi.</p>
            <p>Chúng tôi sẽ liên hệ với bạn sớm nhất qua số điện thoại để xác nhận đơn hàng!</p>
            <span>Tiếp tục mua sắm </span>
            <a asp-action="Index" asp-controller="Home">Trang chủ</a>
        </div>
    </div>
</div>