src/WebApps/CosmeticEshop/Models/Header.cs
using System.Collections.Generic;

namespace CosmeticEshop.Models
{
    public record Header
    {
        public Header()
        {
            RouteParams = new Dictionary<string, string>();
        }
        public string Controller { get; set; }
        public string Text { get; set; }
        public string Action { get; set; } = "Index";
        public string Area { get; set; }
        public bool Current { get; set; }
        public IDictionary<string, string> RouteParams { get; set; }
    }
}

src/WebApps/CosmeticEshop/Controllers/BlogController.cs
using CosmeticEshop.Extensions;
using CosmeticEshop.Models.Blogs;
using CosmeticEshop.Services.Interfaces;
using CosmeticEshop.ViewModels;

using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

using System.Threading.Tasks;

namespace CosmeticEshop.Controllers
{
    public class BlogController : Controller
    {
        private readonly IBasketService _basketService;
        private readonly ISystemService _systemService;
        private readonly IBlogService _blogService;

        private readonly ILogger<BlogController> _logger;

        public BlogController(IBasketService basketService, ISystemService systemService, IBlogService blogService, ILogger<BlogController> logger)
        {
            _basketService = basketService;
            _systemService = systemService;
            _blogService = blogService;
            _logger = logger;
        }

        public async Task<IActionResult> Index(BlogSearchParams @params)
        {
            var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
            var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            ViewBag.shopContact = shopContact;
            ViewBag.menus = menus;
            ViewBag.basket = basket;

            var blogs = await _blogService.SearchBlogsAsync(@params: null);
            ViewBag.Blogs = blogs;
            return View(@params ?? new BlogSearchParams());
        }

        public async Task<IActionResult> Detail(int id)
        {
            var shopContact = await SessionExtensions.GetContactInformationAsync(HttpContext, _systemService);
            var menus = await SessionExtensions.GetMenusAsync(HttpContext, _systemService);
            var basket = await SessionExtensions.GetBasketAsync(HttpContext, _basketService);

            ViewBag.shopContact = shopContact;
            ViewBag.menus = menus;
            ViewBag.basket = basket;

            var blog = await _blogService.GetDetailAsync(id);
            var relatedBlogs = await _blogService.GetRelatedBlogsAsync(id);

            ViewBag.RelatedBlogs = relatedBlogs;
            return View(blog);
        }
    }
}

src/WebApps/CosmeticEshop/Views/Shared/_BlogCartView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CosmeticEshop.Models.Blogs.BlogCardModel
@{
}

<!-- Start Single Blog Item -->
<div class="col-12 text-center">
    <div class="single-blog-post-wrap">
        <figure class="blog-post-thumbnail">
            <a asp-action="Detail" asp-controller="Blog" asp-route-id="@Model.Id"><img src="@Model.ImagePath" alt="@Model.Name" /></a>
        </figure>
        <div class="blog-post-content">
            <div class="blog-meta">
                <a href="#" class="author">By @Model.Author</a>
                <span> - </span>
                <a asp-action="Detail" asp-controller="Blog" asp-route-id="@Model.Id" class="date">@Model.CreatedDate.ToString("MMM dd, yyyy")</a>
            </div>
            <h2><a asp-action="Detail" asp-controller="Blog" asp-route-id="@Model.Id">@Model.Name</a></h2>
            <p>@Model.ShortDescription</p>
            <a asp-action="Detail" asp-controller="Blog" asp-route-id="@Model.Id" class="btn btn-transparent">Read More</a>
        </div>
    </div>
</div>
<!-- End Single Blog Item -->

src/WebApps/CosmeticEshop/Views/Shared/_Header.cshtml
@model IEnumerable<CosmeticEshop.Models.Header>

<ul class="d-flex justify-content-center">
    @foreach (var header in @Model)
    {
        if (header.Current)
        {
            <li><a href="#" class="active">@header.Text</a></li>
        }
        else
        {
            <li><a asp-area="@header.Area" asp-controller="@header.Controller" asp-action="@header.Action" asp-all-route-data="@header.RouteParams">@header.Text</a></li>
        }
    }
</ul>

src/WebApps/CosmeticEshop/Views/Shared/_MiniCartView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CosmeticEshop.Models.Baskets.Basket
@{
}

<!--== Start Mini Cart Wrapper ==-->
<div class="mfp-hide modal-minicart min-w-400" id="miniCart-popup">
    <div class="minicart-content-wrap">
        <h2>Giỏ hàng</h2>
        <div class="minicart-product-list">
            @foreach (var item in Model.Items)
            {
                <!-- Start Single Product -->
                <div class="single-product-item d-flex" id="minicart-@item.ProductId">
                    <figure class="product-thumb">
                        <a asp-action="detail" asp-controller="product" asp-route-id="@item.ProductId"><img src="@item.ImageFile" alt="@item.ProductName"></a>
                    </figure>
                    <div class="product-details">
                        <h2 class="product-title"><a asp-action="detail" asp-controller="product" asp-route-id="@item.ProductId">@item.ProductName</a></h2>
                        <div class="prod-cal d-flex align-items-center">
                            <span class="quantity">@item.Quantity</span>
                            <span class="multiplication">&#215;</span>
                            <span class="price">@((item.Price - item.Sale).ToVNString())</span>
                        </div>
                    </div>
                    <a href="javascript:void(0);" onclick="removeItem('@item.ProductId')" class="remove-icon">&#215;</a>
                </div>
                <!-- End Single Product -->
            }
        </div>
        <div class="minicart-calculation-wrap d-flex justify-content-between align-items-center">
            <span class="cal-title">Tổng tạm tính:</span>
            <span class="cal-amount">@Model.Items.Sum(x => x.Price * x.Quantity).ToVNString()</span>
        </div>
        <div class="minicart-btn-group mt-38">
            <a asp-action="index" asp-controller="basket" class="btn btn-black ">Xem giỏ hàng</a>
            <a asp-action="checkout" asp-controller="basket" class="btn btn-black mt-10">Thanh toán</a>
        </div>
    </div>
</div>
<!--== End Mini Cart Wrapper ==-->

src/WebApps/CosmeticEshop/Views/Shared/_ProductCartView.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CosmeticEshop.Models.Product.ProductCardModel
@using CosmeticEshop.Extensions;
@{
}

<!-- Start Single Product -->
<div class="col-lg-3 col-sm-6">
    <div class="single-product-wrap">
        <!-- Product Thumbnail -->
        <figure class="product-thumbnail">
            <a asp-action="Detail" asp-route-id="@Model.Id" class="d-block">
                <img class="primary-thumb" src="@Model.ImageCardUrl"
                     alt="Product" />
                <img class="secondary-thumb" src="@Model.ImageCardUrl"
                     alt="Product" />
            </a>
            @if(Model.Price > 0)
            {
                <figcaption class="product-hvr-content">
                    <a href="javascript:void(0);" onclick="addToCart('@Model.Id', 1)" class="btn btn-black btn-addToCart">Thêm vào giỏ hàng</a>
                    <div class="prod-btn-group">
                        <span data-toggle="tooltip" data-placement="top" title="Quick Shop">
                            <button data-toggle="modal" onclick="quickViewModal('@Model.Id')" data-target="#quickViewModal">
                                <i class="dl-icon-view"></i>
                            </button>
                        </span>
                        @*<a href="wishlist.html" data-toggle="tooltip" data-placement="top"
                            title="Add to Wishlist"><i class="dl-icon-heart4"></i></a>*@
                    </div>
                    @if (Model.Sale > 0)
                    {
                        <span class="product-badge sale">-@((int)(Model.Sale / Model.Price * 100))%</span>
                    }
                </figcaption>
            }
        </figure>

        <!-- Product Details -->
        <div class="product-details">
            <h2 class="product-name"><a asp-action="Detail" asp-route-id="@Model.Id">@Model.Name</a></h2>
            <div class="product-prices">
                <!-- Check if price = 0  then display "Lien he"-->
                @if (Model.Price == 0)
                {
                }
                else if (Model.Sale > 0)
                {
                    <del class="oldPrice">@Model.Price.ToVNString()</del>
                    <span class="price">@((Model.Price - Model.Sale).ToVNString())</span>
                }
                else
                {
                    <span class="price">@Model.Price.ToVNString()</span>
                }
            </div>
            <div class="list-view-content">
                <div class="list-btn-group mt-30 mt-sm-14">
                    <p class="product-desc">@Model.Summary</p>
                    @if (Model.Price > 0)
                    {
                        <a href="javascript:void(0);" onclick="addToCart('@Model.Id', 1)" class="btn btn-black">Thêm vào giỏ hàng</a>
                    }
                    else
                    {
                        var phone = SessionExtensions.GetContactPhone(Context);
                        <a href="tel:@phone" class="btn btn-black">Liên hệ</a>
                    }
                    <!--
        <a href="wishlist.html" data-toggle="tooltip" data-placement="top"
           title="Add to wishlist"><i class="dl-icon-heart2"></i></a>
    -->
                </div>
            </div>
        </div>
    </div>
</div>
<!-- End Single Product -->

src/WebApps/CosmeticEshop/Views/Shared/_ShareProductSocial.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model CosmeticEshop.Models.Product.ProductDetailModel
@{
    var currentLink = Context.Request.Host.Value;
    var currentScheme = Context.Request.Scheme;
    var shareFb = $"http://www.facebook.com/sharer/sharer.php?u={currentScheme}://{currentLink}/product/detail/{Model.Id}";
}

<dl class="social-share">
    <dt>Chia sẻ với</dt>
    <dd><a href="@shareFb"><i class="fa fa-facebook"></i></a></dd>
    <dd><a href="#"><i class="fa fa-instagram"></i></a></dd>
</dl>